# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3jAfNDkvlIaGYgUVTllwU3q9DdRTQpT
"""

import pandas as pd
import numpy as np
from google.colab import files
from google.colab import drive
import os

# Hubungkan Google Drive
drive.mount('/content/drive')

print(os.listdir('/content/drive/MyDrive/UAS_ETL'))
# Folder output ETL
folder_path = "/content/drive/MyDrive/UAS_ETL"
os.makedirs(folder_path, exist_ok=True)

# ==================================================
# 2. EXTRACT DATA
# Membaca dataset dari Google Drive
# ==================================================

dbd21 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Data_DBD_2021.csv')
dbd22 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Data_DBD_2022.csv')
dbd23 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Data_DBD_2023.csv')
dbd24 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Data_DBD_2024.csv')

air21 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Persentase Rumah Tangga yang Memiliki Akses terhadap Sumber Air Minum Layak Menurut Provinsi dan Klasifikasi Desa, 2021.csv')
air22 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Persentase Rumah Tangga yang Memiliki Akses terhadap Sumber Air Minum Layak Menurut Provinsi dan Klasifikasi Desa, 2022.csv')
air23 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Persentase Rumah Tangga yang Memiliki Akses terhadap Sumber Air Minum Layak Menurut Provinsi dan Klasifikasi Desa, 2023.csv')
air24 = pd.read_csv('/content/drive/MyDrive/UAS_ETL/Persentase Rumah Tangga yang Memiliki Akses terhadap Sumber Air Minum Layak Menurut Provinsi dan Klasifikasi Desa, 2024.csv')

# ==================================================
# Membaca data
# ==================================================
print("DBD 2021 :", dbd21.shape)
print("DBD 2022 :", dbd22.shape)
print("DBD 2023 :", dbd23.shape)
print("DBD 2024 :", dbd24.shape)

print("AIR 2021 :", air21.shape)
print("AIR 2022 :", air22.shape)
print("AIR 2023 :", air23.shape)
print("AIR 2024 :", air24.shape)

# ==================================================
# 3. ADD YEAR
# ==================================================

dbd21['Tahun'] = 2021
dbd22['Tahun'] = 2022
dbd23['Tahun'] = 2023
dbd24['Tahun'] = 2024

air21['Tahun'] = 2021
air22['Tahun'] = 2022
air23['Tahun'] = 2023
air24['Tahun'] = 2024

# ==================================================
# 4. CONCAT DATA
# Menggabungkan data seluruh tahun
# ==================================================

dbd = pd.concat(
    [dbd21, dbd22, dbd23, dbd24],
    ignore_index=True
)

air = pd.concat(
    [air21, air22, air23, air24],
    ignore_index=True
)

# ==================================================
# 5. DATA CLEANING
# Menghapus missing value dan data duplikat
# ==================================================

def clean_dataframe(df):

    df = df.dropna()

    df = df.drop_duplicates()

    return df

dbd = clean_dataframe(dbd)
air = clean_dataframe(air)

# ==================================================
# 6. STANDARDIZE DATA
# Menyeragamkan format nama provinsi
# ==================================================

dbd['Provinsi'] = (
    dbd['Provinsi']
    .str.upper()
    .str.strip()
)

air['38 Provinsi'] = (
    air['38 Provinsi']
    .str.upper()
    .str.strip()
)

# ==================================================
# 7. SELECT COLUMN
# Memilih kolom yang dibutuhkan
# ==================================================

dbd = dbd[
    ['Provinsi','Tahun','Jumlah Kasus']
]

air = air[
    ['38 Provinsi','Tahun','Unnamed: 3']
]

# ==================================================
# 8. DATA INTEGRATION
# Menggabungkan data DBD dan Air Minum
# ==================================================

# 1. Hapus agregat nasional
air = air[air['38 Provinsi'] != 'INDONESIA']

# 2. Samakan nama provinsi
air['38 Provinsi'] = air['38 Provinsi'].replace({
    'KEP. BANGKA BELITUNG': 'KEPULAUAN BANGKA BELITUNG',
    'KEP. RIAU': 'KEPULAUAN RIAU'
})

# 3. Cek kesesuaian provinsi
provinsi_dbd = set(dbd['Provinsi'].unique())
provinsi_air = set(air['38 Provinsi'].unique())

hilang = provinsi_dbd - provinsi_air

print("Provinsi yang hilang:")
print(hilang)

# 4. Merge data
data_final = pd.merge(
    dbd,
    air,
    left_on=['Provinsi','Tahun'],
    right_on=['38 Provinsi','Tahun'],
    how='inner'
)

# ==================================================
# 9. DATA QUALITY REPORT
# ==================================================

print("Jumlah Data :", len(data_final))

print(
    "Jumlah Provinsi :",
    data_final['Provinsi'].nunique()
)

print(
    "Rentang Tahun :",
    data_final['Tahun'].min(),
    "-",
    data_final['Tahun'].max()
)

print(
    "Missing Value :",
    data_final.isnull().sum().sum()
)

print(
    "Duplicate Data :",
    data_final.duplicated().sum()
)

# ==================================================
# 10. FINAL TRANSFORMATION
# Membersihkan dan mengganti nama kolom
# ==================================================

# The columns '38 Provinsi' and 'Unnamed: 3' were already handled
# by previous cells (k1fMupPx8bOQ and 5SB6Quylzlo9).
# Therefore, the initial drop and rename operations are redundant here.

# Rename 'Unnamed: 3' to 'Akses_Air_Minum' before using it
data_final = data_final.rename(columns={'Unnamed: 3': 'Akses_Air_Minum'})

data_final['Akses_Air_Minum'] = pd.to_numeric(
    data_final['Akses_Air_Minum'],
    errors='coerce'
)

data_final = data_final.dropna()

print(data_final.info())
print(data_final.head())
print(data_final.shape)

print(data_final.isnull().sum())

print(data_final.info())

print(data_final['Provinsi'].nunique())

print(sorted(data_final['Tahun'].unique()))

print("=== DATA QUALITY REPORT ===")

print("Shape :", data_final.shape)

# ==================================================
# 11. STANDARDIZE COLUMN NAME
# ==================================================

# Step 1: Rename 'Jumlah Kasus' to 'Jumlah_Kasus' for consistency
if 'Jumlah Kasus' in data_final.columns:
    data_final = data_final.rename(columns={'Jumlah Kasus': 'Jumlah_Kasus'})
else:
    print("Warning: 'Jumlah Kasus' column not found for renaming in 5SB6Quylzlo9. Check previous steps.")

# Step 2: Drop '38 Provinsi' as it's redundant after merge and not needed for final output
if '38 Provinsi' in data_final.columns:
    data_final = data_final.drop(columns=['38 Provinsi'])
else:
    print("Warning: '38 Provinsi' column not found for dropping in 5SB6Quylzlo9. Check previous steps.")

# Step 3: Explicitly select and order the columns to be passed to the next stage
# This ensures only desired columns are kept and in a specific order
final_columns_after_5SB6Quylzlo9 = ['Provinsi', 'Tahun', 'Jumlah_Kasus', 'Akses_Air_Minum']

# Verify all desired columns are present before selection
missing_cols_pre_filter = [col for col in final_columns_after_5SB6Quylzlo9 if col not in data_final.columns]
if missing_cols_pre_filter:
    print(f"Error: Columns {missing_cols_pre_filter} are missing in data_final before final selection in cell 5SB6Quylzlo9. Data_final will be empty.")
    data_final = pd.DataFrame(columns=final_columns_after_5SB6Quylzlo9) # Create an empty DataFrame to prevent downstream errors
else:
    data_final = data_final[final_columns_after_5SB6Quylzlo9]

print("Columns after 5SB6Quylzlo9:", data_final.columns)

# ==================================================
# 12. EXPORT DATA
# Menyimpan hasil ETL ke CSV
# ==================================================

output_file = (
    '/content/drive/MyDrive/UAS_ETL/'
    'hasil_etl_dbd_airminum.csv'
)

data_final.to_csv(
    output_file,
    index=False
)
print("File berhasil disimpan ke Google Drive")

# ==================================================
# 13. LOAD DATA TO DATABASE
# Memuat hasil ETL ke MySQL Aiven
# ==================================================
!pip install sqlalchemy psycopg2-binary pymysql

from sqlalchemy import create_engine

def connect_aiven():

    DATABASE_URL = (
        "mysql+pymysql://avnadmin:AVNS_c6K9EHiaWNQ2cyyu6we"
        "@mysql-4c516e3-data-engineering.d.aivencloud.com:19977/defaultdb"
    )

    engine = create_engine(
        DATABASE_URL,
        connect_args={
            "ssl": {
                "ssl_mode": "REQUIRED"
            }
        }
    )

    return engine

from sqlalchemy import text

def create_table(engine):

    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS dbd_airminum (
                id INT PRIMARY KEY,
                Provinsi VARCHAR(100),
                Tahun INT,
                Jumlah_Kasus INT,
                Akses_Air_Minum FLOAT
            )
        """))

    print("Tabel berhasil dibuat")

if 'id' not in data_final.columns:
    data_final.insert(
        0,
        'id',
        range(1, len(data_final)+1)
    )

# ==================================================
# 12. FINAL COLUMN RENAMING AND ORDERING FOR DATABASE
# ==================================================

# Step 1: Rename columns to lowercase for the database
column_rename_map = {
    'Provinsi': 'provinsi',
    'Tahun': 'tahun',
    'Jumlah_Kasus': 'jumlah_kasus',
    'Akses_Air_Minum': 'akses_air_minum'
}
data_final = data_final.rename(columns=column_rename_map)

# Step 2: Explicitly select and order the columns, excluding 'id' which is added later
final_columns_for_db_pre_id = ['provinsi', 'tahun', 'jumlah_kasus', 'akses_air_minum']

# Verify all desired columns are present before selection
missing_cols_pre_filter = [col for col in final_columns_for_db_pre_id if col not in data_final.columns]
if missing_cols_pre_filter:
    print(f"Error: Columns {missing_cols_pre_filter} are missing in data_final before final selection in cell F3IwRkvDrGTf. Data_final will be empty.")
    data_final = pd.DataFrame(columns=final_columns_for_db_pre_id) # Create an empty DataFrame to prevent downstream errors
else:
    data_final = data_final[final_columns_for_db_pre_id]

print("Columns after F3IwRkvDrGTf:", data_final.columns)
print("Data types after F3IwRkvDrGTf:")
print(data_final.dtypes)

from sqlalchemy import text

engine = connect_aiven()

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS dbd_airminum"))

def create_table(engine):

    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS dbd_airminum (
                id INT PRIMARY KEY,
                provinsi VARCHAR(100),
                tahun INT,
                jumlah_kasus INT,
                akses_air_minum FLOAT
            )
        """))

    print("Tabel berhasil dibuat")

def load_data(engine, df):

    df.to_sql(
        "dbd_airminum",
        engine,
        if_exists="append",
        index=False,
        chunksize=1000,
        method="multi"
    )

    print("Data berhasil dikirim ke Aiven")

import pandas as pd

def check_data(engine):

    query = """
    SELECT *
    FROM dbd_airminum
    LIMIT 10
    """

    return pd.read_sql(query, engine)

print(data_final.columns)
print(data_final.dtypes)
print(data_final.columns.tolist())

# ==================================================
# 14. DATA VERIFICATION
# Memastikan data berhasil masuk ke Aiven
# ==================================================

engine = connect_aiven()

create_table(engine)

load_data(engine, data_final)

print(check_data(engine))